import { useEffect, useRef, useState } from "react";
import {
  ArrowRight,
  BookOpen,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Facebook,
  GraduationCap,
  HeartPulse,
  Instagram,
  Landmark,
  Menu,
  Search,
  ShieldCheck,
  Sparkles,
  Users,
  X,
  Youtube,
} from "lucide-react";

type IconType = typeof CalendarDays;

const news = [
  { title: "Sciences : ouvrir la voie avec Elsa Lubek", text: "Elles cherchent, enseignent, innovent, bousculent les idées reçues. Toutes dans l’équation donnent la parole à des femmes qui ont choisi les sciences.", tone: "coral", tag: "Portrait", image: "portrait" },
  { title: "Priorités pour l’année scolaire 2026-2027", text: "La circulaire de rentrée présente les priorités de l’année scolaire : instruire, protéger et donner à chacun les moyens de réussir.", tone: "navy", tag: "Actualité", image: "flag" },
  { title: "Rapport 2025 de la médiatrice de l’Éducation nationale et de l’Enseignement supérieur", text: "Catherine Becchetti-Bizot présente son rapport 2025 intitulé « Porter attention aux vulnérabilités, agir en faveur de la santé mentale. »", tone: "yellow", tag: "Publication" },
  { title: "Agir pour la santé mentale des enfants et des jeunes", text: "D’après l’OMS, la santé mentale est un état de bien-être qui permet à chacun de réaliser son potentiel.", tone: "sky", tag: "Dossier" },
];

const services: { title: string; icon: IconType }[] = [
  { title: "Le calendrier scolaire", icon: CalendarDays },
  { title: "Les bourses de collège et de lycée", icon: Landmark },
  { title: "La lutte contre le harcèlement", icon: ShieldCheck },
  { title: "La préparation du bac et l’orientation", icon: GraduationCap },
  { title: "La santé et le bien-être des élèves", icon: HeartPulse },
  { title: "Les élèves à besoins éducatifs particuliers", icon: Users },
];

const rentrée = [
  { title: "L’allocation de rentrée scolaire", text: "L’allocation de rentrée scolaire (ARS) est versée, sous conditions de ressources, aux familles ayant au moins un enfant scolarisé âgé de 6 à 18 ans.", image: "child" },
  { title: "Calendrier scolaire", text: "Retrouvez ici toutes les dates essentielles de l’année scolaire 2026-2027 : périodes de cours, vacances et jours fériés.", image: "playground" },
  { title: "Faire sa demande de bourse", text: "Vous n'avez pas consenti à l'étude automatique du droit à bourse au moment de l'inscription ? Vous pouvez faire une demande annuelle.", },
  { title: "Les fournitures scolaires", text: "La réduction des charges financières qui pèsent sur les familles à chaque rentrée scolaire constitue une priorité.", },
];

const footerGroups = [
  { title: "Sites Éducation", links: ["Devenir enseignant", "Éduscol", "Onisep", "Cned", "Réseau Canopé", "CLEMI", "France Éducation international", "Sites académiques"] },
  { title: "Rapports, publications et statistiques", links: ["Data.education.gouv.fr", "Conseil d’évaluation de l’École", "Conseil supérieur des programmes", "Direction de l’évaluation, de la prospective et de la performance", "Inspection générale de l’éducation, du sport et de la recherche"] },
];

function ArrowLink({ children }: { children: React.ReactNode }) {
  return <a href="#contact" className="arrow-link">{children}<ArrowRight size={18} aria-hidden="true" /></a>;
}

function Visual({ variant }: { variant: string }) {
  return <div className={`visual visual-${variant}`} role="img" aria-label="Illustration éditoriale de l’Éducation nationale"><div className="visual-shape shape-a" /><div className="visual-shape shape-b" /><div className="visual-caption">{variant === "hero" ? "LIRE · IMAGINER · GRANDIR" : "ÉDUQUER · ACCOMPAGNER"}</div></div>;
}

export function EducationHomepage() {
  const [searchOpen, setSearchOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [searched, setSearched] = useState(false);
  const [cookies, setCookies] = useState(true);
  const [cookieDetail, setCookieDetail] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") { setMenuOpen(false); setSearchOpen(false); }
    };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = menuOpen ? "hidden" : "";
    return () => { window.removeEventListener("keydown", onKey); document.body.style.overflow = ""; };
  }, [menuOpen]);
  useEffect(() => { if (searchOpen) searchRef.current?.focus(); }, [searchOpen]);

  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setSearched(true); };

  return (
    <div className="education-page">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap');
        .education-page{--blue:#080b72;--ink:#151519;--yellow:#ffd52e;--paper:#fbfaf7;--cream:#fff0c7;--line:#d9d9d4;min-height:100vh;background:var(--paper);color:var(--ink);font-family:'DM Sans',sans-serif;font-size:15px;line-height:1.48}
        .education-page *{box-sizing:border-box}.education-page a{color:inherit;text-decoration:none}.education-page button,.education-page input{font:inherit}.container{max-width:1200px;margin:auto;padding:0 28px}
        .skip-links{position:absolute;z-index:20;left:12px;top:0;display:flex;gap:8px;transform:translateY(-120%);transition:.2s}.skip-links:focus-within{transform:translateY(10px)}.skip-links a{background:var(--blue);color:#fff;padding:10px 14px;font-weight:700}
        .topline{border-top:5px solid var(--yellow);border-bottom:1px solid var(--line);background:#fff}.topline-inner{height:108px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:flex-start;gap:12px;color:var(--blue);font-weight:700;line-height:1.02;letter-spacing:-.04em;font-size:18px}.brand-mark{width:27px;height:27px;background:linear-gradient(90deg,#13227c 0 33%,#fff 33% 66%,#ed2939 66%);border:1px solid #ddd;margin-top:2px}.brand small{display:block;font-family:'Space Mono';font-size:7px;letter-spacing:0;margin-top:7px;color:#444}.top-links{align-self:flex-start;margin-top:9px;display:flex;gap:27px;color:var(--blue);font-size:13px}.top-actions{display:flex;align-items:center;gap:14px}.search-trigger,.menu-trigger{border:0;background:none;color:var(--blue);cursor:pointer;display:flex;align-items:center;gap:7px;min-height:44px;font-weight:700}.search-trigger{font-size:14px}.search-panel{background:#f2f0ec;border-top:1px solid var(--line);padding:20px 0}.search-form{display:flex;max-width:760px}.search-form label{position:absolute;left:-10000px}.search-form input{flex:1;border:1px solid var(--blue);border-right:0;padding:13px 16px;background:#fff;outline:none}.search-form button{background:var(--blue);color:#fff;border:0;padding:0 18px;cursor:pointer}.search-result{max-width:760px;margin:12px 0 0;color:var(--blue);font-size:14px}
        .nav{border-bottom:1px solid var(--line);background:#fff}.nav-inner{display:flex;align-items:center;gap:34px;min-height:57px}.nav a{font-size:14px;font-weight:600;padding:18px 0}.nav a:hover,.nav a:focus-visible{color:var(--blue)}.nav-chevron{margin-left:5px;vertical-align:middle}.mobile-menu{display:none}
        .hero-wrap{background:var(--yellow);padding:42px 0 50px}.hero{display:grid;grid-template-columns:1.1fr .9fr;min-height:390px;align-items:center}.hero-copy{background:#fff;padding:42px 46px;position:relative;z-index:1;margin-right:-45px;box-shadow:0 12px 0 rgba(8,11,114,.09)}.eyebrow{font-family:'Space Mono';font-size:11px;text-transform:uppercase;color:var(--blue);letter-spacing:.08em;font-weight:700}.hero h1{font-size:clamp(2.4rem,4.5vw,4.55rem);line-height:.98;letter-spacing:-.07em;max-width:600px;margin:16px 0 22px}.hero p{max-width:500px;font-size:17px;color:#45454b}.outline-btn{display:inline-flex;align-items:center;gap:10px;border:1.5px solid var(--blue);color:var(--blue);padding:12px 17px;font-weight:700;margin-top:22px;min-height:46px;transition:.2s}.outline-btn:hover,.outline-btn:focus-visible{background:var(--blue);color:#fff}.visual{height:390px;position:relative;overflow:hidden;background:#35b9b1}.visual-hero{background:#39b9b0}.visual-shape{position:absolute}.visual-hero .shape-a{width:60%;height:130%;right:-9%;top:-13%;background:#ffdc29;transform:rotate(19deg)}.visual-hero .shape-b{width:38%;height:42%;left:16%;bottom:-8%;background:var(--blue);border-radius:52% 48% 0 0;transform:rotate(-13deg)}.visual-caption{position:absolute;left:30px;bottom:30px;color:var(--blue);font-size:clamp(23px,3vw,42px);font-weight:700;line-height:.9;max-width:190px;letter-spacing:-.07em;transform:rotate(-8deg)}
        section{padding:64px 0}.section-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:28px;gap:20px}.section-heading h2{font-size:clamp(2rem,3vw,3rem);line-height:1;letter-spacing:-.06em;margin:0}.section-heading p{max-width:420px;margin:0;color:#555}.blue-link{color:var(--blue);font-weight:700;text-decoration:underline;text-underline-offset:3px}
        .news-grid{display:grid;grid-template-columns:1.18fr 1.18fr 1fr;gap:20px}.news-card{border:1px solid var(--line);background:#fff;min-height:245px;display:flex;flex-direction:column;transition:transform .2s,box-shadow .2s}.news-card:hover,.news-card:focus-within{transform:translateY(-4px);box-shadow:5px 5px 0 var(--yellow)}.news-card.featured{grid-row:span 2}.news-image{height:175px;background:#d6c9b6;position:relative;overflow:hidden}.news-image.flag{background:#2e4073}.news-image.flag:after{content:'2026—27';position:absolute;color:#fff;font-size:34px;font-weight:700;left:22px;bottom:19px}.news-image.portrait:after{content:'ELSA';position:absolute;color:#fff;font-size:54px;font-weight:700;right:18px;bottom:8px;transform:rotate(-8deg)}.news-image:before{content:'';position:absolute;width:52%;height:150%;background:#ee896a;left:15%;top:-22%;transform:rotate(20deg)}.news-image.flag:before{background:#e8c63f;left:65%}.news-body{padding:23px 25px;display:flex;flex:1;flex-direction:column}.news-body h3{font-size:20px;line-height:1.12;margin:0 0 12px;color:var(--blue);letter-spacing:-.03em}.news-body p{margin:0;color:#555}.tag{font-family:'Space Mono';color:var(--blue);font-size:10px;text-transform:uppercase;margin-bottom:10px}.news-card:not(.featured) .news-body{min-height:175px}.news-card:not(.featured) .news-body .arrow-link{margin-top:auto}
        .services-section,.people-section{background:var(--cream)}.service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.service-card,.quick-card{background:#fff;border:1px solid var(--line);border-bottom:4px solid var(--blue);min-height:125px;padding:24px 23px;display:flex;align-items:center;gap:17px;color:var(--blue);transition:.2s}.service-card:hover,.service-card:focus-visible{background:var(--blue);color:#fff;transform:translateY(-3px)}.service-card svg{flex:none;width:39px;height:39px;stroke-width:1.4}.service-card strong{font-size:17px;line-height:1.15}.arrow-link{display:flex;align-items:center;justify-content:space-between;gap:14px;color:var(--blue);font-weight:700;min-height:44px}.arrow-link svg{flex:none;transition:transform .2s}.arrow-link:hover svg,.arrow-link:focus-visible svg{transform:translateX(5px)}
        .rentrée-grid{display:grid;grid-template-columns:1.15fr 1.15fr 1fr;gap:20px}.rentrée-card{border:1px solid var(--line);background:#fff;display:flex;flex-direction:column}.rentrée-card .news-body{min-height:190px}.rentrée-card h3{color:var(--blue)}.rentrée-card.simple{padding:25px}.rentrée-card.simple .news-body{padding:0;min-height:155px}.rentrée-card.simple .arrow-link{margin-top:auto}.mini-visual{height:170px;background:#ee967a;position:relative;overflow:hidden}.mini-visual.playground{background:#83b3c2}.mini-visual:before{content:'✦';position:absolute;font-size:120px;color:#ffc927;right:30px;top:-18px}.mini-visual:after{content:'';position:absolute;width:55%;height:90%;background:#e94864;border-radius:50% 50% 0 0;left:20%;bottom:-35%;transform:rotate(-12deg)}.mini-visual.playground:after{background:#f3cf3e}
        .people-grid{display:grid;grid-template-columns:1.15fr 1.15fr;gap:20px}.people-feature{background:#fff;border:1px solid var(--line)}.people-feature .visual{height:240px;background:#d6b89d}.people-feature .visual-caption{font-size:30px}.people-feature .news-body{min-height:210px}.people-feature h3{color:var(--blue);font-size:22px}.people-links{display:grid;grid-template-columns:1fr 1fr;gap:18px}.quick-card{min-height:120px;text-align:center;justify-content:center;font-size:16px}.quick-card:hover{transform:translateY(-3px);background:#fff;box-shadow:4px 4px 0 var(--blue)}
        .experiences{background:var(--blue);color:#fff}.experiences .section-heading p{color:#d7d8fa}.experiences .eyebrow,.experiences .blue-link{color:var(--yellow)}.experience-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px}.experience-card{background:#171b83;border:1px solid #4f53a1;min-height:230px;padding:26px;display:flex;flex-direction:column;transition:.2s}.experience-card:hover{transform:translateY(-4px);background:#23288f}.experience-card h3{font-size:21px;line-height:1.1;margin:8px 0 12px;letter-spacing:-.03em}.experience-card p{color:#d8daf1}.experience-card .arrow-link{color:var(--yellow);margin-top:auto}
        .contact-section{background:#f2f0ec}.contact-grid{display:grid;grid-template-columns:1fr 2fr;gap:50px}.contact-grid h2{font-size:clamp(2rem,3vw,3rem);letter-spacing:-.06em;line-height:1;margin:0 0 15px}.contact-grid p{color:#555;max-width:340px}.contact-links{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #bdbdb8}.contact-links a{padding:17px 10px 17px 0;border-bottom:1px solid #bdbdb8;color:var(--blue);font-weight:700;min-height:70px}.social{border-top:1px solid #c8c8c4;padding-top:32px;margin-top:25px}.social h2{font-size:21px;letter-spacing:-.03em}.social-links{display:flex;flex-wrap:wrap;gap:10px}.social-links a{border:1px solid #bdbdb8;padding:10px 15px;display:flex;align-items:center;gap:8px;color:var(--blue);font-weight:700}.social-links a:hover{background:var(--blue);color:#fff}
        footer{background:#11134f;color:#fff}footer .container{padding-top:52px;padding-bottom:35px}.footer-groups{display:grid;grid-template-columns:1fr 1fr;gap:60px;padding-bottom:38px;border-bottom:1px solid #555996}.footer-group h2{font-size:18px;color:var(--yellow);margin:0 0 20px}.footer-group ul{list-style:none;padding:0;margin:0;columns:2;column-gap:30px}.footer-group li{break-inside:avoid;margin-bottom:10px}.footer-group a{color:#e8e8fa;font-size:14px}.footer-group a:hover{text-decoration:underline}.footer-bottom{display:flex;justify-content:space-between;gap:30px;padding-top:30px}.footer-signature{font-size:18px;font-weight:700;line-height:1.05}.footer-signature small{font-family:'Space Mono';font-size:8px;display:block;margin-top:8px;color:#c6c8e6}.legal{display:flex;flex-wrap:wrap;gap:10px 22px;max-width:720px}.legal a{color:#e8e8fa;font-size:13px}.legal a:hover{color:var(--yellow)}.cookie{position:fixed;z-index:10;bottom:16px;left:16px;right:16px;max-width:720px;background:#fff;border:2px solid var(--blue);box-shadow:8px 8px 0 rgba(8,11,114,.18);padding:22px}.cookie h2{margin:0;color:var(--blue);font-size:20px}.cookie p{margin:8px 0;color:#444;font-size:14px}.cookie-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:15px}.cookie button{min-height:44px;padding:10px 16px;border:1px solid var(--blue);color:var(--blue);background:#fff;cursor:pointer;font-weight:700}.cookie button.primary{background:var(--blue);color:#fff}.cookie button:hover{transform:translateY(-2px)}.cookie-close{position:absolute;right:8px;top:8px;border:0;background:none;color:var(--blue);cursor:pointer}
        :focus-visible{outline:3px solid #ef8b22;outline-offset:3px}@media(max-width:800px){.container{padding:0 18px}.topline-inner{height:82px}.top-links{display:none}.brand{font-size:15px}.nav{display:none}.mobile-menu{display:block;position:fixed;z-index:9;inset:0;background:var(--blue);color:#fff;padding:100px 25px 30px}.mobile-menu button{position:absolute;right:18px;top:25px;background:none;border:0;color:#fff}.mobile-menu a{display:block;font-size:25px;padding:13px 0;border-bottom:1px solid #484caa}.top-actions .search-trigger span{display:none}.hero-wrap{padding:22px 0 30px}.hero{display:flex;flex-direction:column-reverse}.hero-copy{margin:0;padding:28px 23px;width:calc(100% - 18px);align-self:flex-start;box-shadow:6px 7px 0 rgba(8,11,114,.15)}.visual{height:260px;width:100%}.hero h1{font-size:2.75rem}.hero p{font-size:15px}.section-heading{display:block}.section-heading h2{margin-bottom:13px}.news-grid,.rentrée-grid,.people-grid,.contact-grid{grid-template-columns:1fr}.news-card.featured{grid-row:auto}.news-card:not(.featured) .news-body{min-height:0}.service-grid{grid-template-columns:1fr 1fr;gap:10px}.service-card{padding:16px 13px;min-height:112px;gap:10px}.service-card strong{font-size:14px}.service-card svg{width:31px}.people-links{gap:10px}.quick-card{min-height:105px;padding:15px 8px;font-size:14px}.experience-grid{grid-template-columns:1fr}.contact-links{grid-template-columns:1fr 1fr}.footer-groups{grid-template-columns:1fr;gap:30px}.footer-group ul{columns:1}.footer-bottom{display:block}.legal{margin-top:25px}.cookie{left:10px;right:10px;bottom:10px}.cookie-actions button{flex:1}.search-panel{padding:15px 0}.search-form{width:100%}}
      `}</style>
      <nav className="skip-links" aria-label="Liens d’évitement"><a href="#main-content">Accéder au contenu principal</a><a href="#page-header--menu">Accéder au menu</a><a href="#search-block-form">Accéder à la recherche</a><a href="#footer">Accéder au pied de page</a></nav>
      <header id="page-header">
        <div className="topline"><div className="container topline-inner"><a className="brand" href="#main-content" aria-label="Ministère de l'Éducation nationale, accueil"><span className="brand-mark" aria-hidden="true" /><span>MINISTÈRE<br />DE L’ÉDUCATION<br />NATIONALE<small>Liberté · Égalité · Fraternité</small></span></a><div><div className="top-links"><a href="#footer">Espace presse</a><a href="#footer">Études et statistiques</a><a href="#services">Parcoursup <ExternalLink size={12} /></a></div><div className="top-actions"><button className="search-trigger" onClick={() => setSearchOpen(v => !v)} aria-expanded={searchOpen} aria-controls="search-block-form"><Search size={19} /> <span>Rechercher</span></button><button className="menu-trigger" onClick={() => setMenuOpen(true)} aria-expanded={menuOpen} aria-controls="page-header--menu"><Menu size={23} /><span>Menu</span></button></div></div></div></div>
        {searchOpen && <div className="search-panel" id="search-block-form"><div className="container"><form className="search-form" onSubmit={submitSearch}><label htmlFor="site-search">Rechercher une information</label><input ref={searchRef} id="site-search" type="search" value={search} onChange={e => { setSearch(e.target.value); setSearched(false); }} placeholder="Rechercher une information, une démarche ou un contact" /><button aria-label="Lancer la recherche"><Search size={20} /></button></form>{searched && <div className="search-result" role="status">{search ? `Résultats pour « ${search} » — consultez les rubriques ci-dessous.` : "Saisissez un terme pour lancer une recherche."}</div>}</div></div>}
        <nav id="page-header--menu" className="nav" aria-label="Navigation principale"><div className="container nav-inner">{["Ministère","Système éducatif","Enseignements","Vie scolaire","Métiers et ressources humaines","Bulletin officiel"].map((item, i) => <a href={i === 3 ? "#services" : "#footer"} key={item}>{item}{i < 5 && <ChevronDown className="nav-chevron" size={14} />}</a>)}</div></nav>
        {menuOpen && <div className="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu principal"><button onClick={() => setMenuOpen(false)} aria-label="Fermer le menu"><X size={28} /></button>{["Ministère","Système éducatif","Enseignements","Vie scolaire","Métiers et ressources humaines","Bulletin officiel"].map(item => <a href="#services" onClick={() => setMenuOpen(false)} key={item}>{item}<ChevronDown size={17} /></a>)}</div>}
      </header>
      <main id="main-content">
        <section className="hero-wrap" aria-labelledby="hero-title"><div className="container hero"><div className="hero-copy"><div className="eyebrow">L’été, la lecture en partage</div><h1 id="hero-title">Inciter les jeunes à voyager par l’imaginaire</h1><p>Romans, poèmes, revues, bandes dessinées, nouvelles ou mangas, cet été tout se lit ! Où que tu sois, voyage dans les librairies ou les bibliothèques.</p><a className="outline-btn" href="#experiences">Lire l’article <ArrowRight size={18} /></a></div><Visual variant="hero" /></div></section>
        <section className="container" aria-labelledby="news-title"><div className="section-heading"><h2 id="news-title">À la une</h2><a className="blue-link" href="#footer">Toutes les actualités</a></div><div className="news-grid">{news.map((item, i) => <article className={`news-card ${i < 2 ? "featured" : ""}`} key={item.title}>{item.image && <div className={`news-image ${item.image}`} aria-hidden="true" />}{!item.image && <div className={`news-image ${item.tone}`} aria-hidden="true" />}{<div className="news-body"><div className="tag">{item.tag}</div><h3><a href="#experiences">{item.title}</a></h3><p>{item.text}</p>{i > 1 && <ArrowLink>Lire la suite</ArrowLink>}</div>}</article>)}</div></section>
        <section className="services-section" id="services" aria-labelledby="services-title"><div className="container"><div className="section-heading"><h2 id="services-title">L’éducation nationale et vous</h2><p>Les informations et démarches essentielles pour les familles, les élèves et les citoyens.</p></div><div className="service-grid">{services.map(({ title, icon: Icon }) => <a className="service-card" href="#contact" key={title}><Icon aria-hidden="true" /><strong>{title}</strong><ArrowRight className="ml-auto" size={19} /></a>)}</div></div></section>
        <section className="container" aria-labelledby="rentrée-title"><div className="section-heading"><h2 id="rentrée-title">Préparer la rentrée</h2><a className="blue-link" href="#contact">Voir toutes les démarches</a></div><div className="rentrée-grid">{rentrée.map((item, i) => <article className={`rentrée-card ${!item.image ? "simple" : ""}`} key={item.title}>{item.image && <div className={`mini-visual ${item.image}`} role="img" aria-label="Illustration de la rentrée scolaire" />}{<div className="news-body"><h3><a href="#contact">{item.title}</a></h3><p>{item.text}</p><ArrowLink>Accéder à la démarche</ArrowLink></div>}</article>)}</div></section>
        <section className="people-section" aria-labelledby="people-title"><div className="container"><div className="section-heading"><h2 id="people-title">Personnels de l’éducation nationale</h2><p>Un accompagnement professionnel personnalisé et confidentiel, à chaque étape de votre parcours.</p></div><div className="people-grid"><article className="people-feature"><Visual variant="people" /><div className="news-body"><h3>Le réseau des conseillers ressources humaines de proximité</h3><p>Vous vous posez des questions sur votre parcours professionnel ou vos perspectives d’évolution ? Le réseau des conseillers ressources humaines de proximité (CRHP) vous permet de bénéficier d’informations, de conseils ou d’un accompagnement personnalisé.</p><ArrowLink>Contacter un conseiller RH de proximité</ArrowLink></div></article><div className="people-links">{["La protection sociale complémentaire","La rémunération des enseignants","I-Prof, l’assistant carrière","L’éventail des missions et métiers pour les enseignants","Le portail mobilité des enseignants","Le Programme national de formation 2026-2027"].map(title => <a className="quick-card" href="#contact" key={title}>{title}<ArrowRight size={18} /></a>)}</div></div></div></section>
        <section className="experiences" id="experiences" aria-labelledby="experiences-title"><div className="container"><div className="section-heading"><div><div className="eyebrow">Culture · sport · découverte</div><h2 id="experiences-title">Des expériences qui forment</h2></div><p>Théâtre, lecture, cinéma, langues, sciences : les actions éducatives ouvrent les horizons et nourrissent la curiosité.</p></div><div className="experience-grid">{["Septembre Bouge : l’activité physique et sportive à l’honneur à la rentrée","La compétition des métiers WorldSkills","Masterclasses de cinéma : découvrir de grands films"].map((title, i) => <article className="experience-card" key={title}><Sparkles size={21} aria-hidden="true" /><h3>{title}</h3><p>{i === 0 ? "Une rentrée pour bouger, partager et prendre soin de sa santé." : i === 1 ? "Des savoir-faire, des talents et une jeunesse qui se révèle." : "Des rencontres pour regarder le monde autrement."}</p><ArrowLink>Découvrir le projet</ArrowLink></article>)}</div></div></section>
        <section className="contact-section" id="contact" aria-labelledby="contact-title"><div className="container contact-grid"><div><h2 id="contact-title">Nous contacter</h2><p>Trouvez rapidement le bon interlocuteur selon votre situation et votre besoin.</p></div><div className="contact-links">{["Les établissements","Le ministre","Le médiateur","Les académies","Scolarité, diplômes, examens, orientation","Concours, emplois, carrières","Le délégué à la protection des données","Autres contacts"].map(item => <a href="#footer" key={item}>{item}<ArrowRight size={17} /></a>)}</div></div><div className="container social"><h2>Suivez-nous sur les réseaux sociaux</h2><div className="social-links"><a href="#footer"><Instagram size={18} /> Instagram</a><a href="#footer"><Facebook size={18} /> Facebook</a><a href="#footer">TikTok</a><a href="#footer">LinkedIn</a><a href="#footer">X</a><a href="#footer"><Youtube size={18} /> YouTube</a><a href="#footer">Bluesky</a></div></div></section>
      </main>
      <footer id="footer"><div className="container"><div className="footer-groups">{footerGroups.map(group => <section className="footer-group" key={group.title} aria-labelledby={group.title}><h2 id={group.title}>{group.title}</h2><ul>{group.links.map(link => <li key={link}><a href="#main-content">{link} <ExternalLink size={11} /></a></li>)}</ul></section>)}</div><div className="footer-bottom"><div className="footer-signature">MINISTÈRE<br />DE L’ÉDUCATION NATIONALE<small>Liberté · Égalité · Fraternité</small></div><div className="legal"><a href="#footer">Espace presse</a><a href="#contact">Contactez-nous</a><a href="#footer">Mentions légales</a><a href="#footer">Données personnelles et cookies</a><a href="#footer" onClick={() => { setCookies(true); setCookieDetail(true); }}>Gestion des cookies</a><a href="#footer">Déclaration d’accessibilité : partiellement conforme</a><a href="#footer">Légifrance</a><a href="#footer">Service-Public.fr</a><a href="#footer">Info.gouv.fr</a><a href="#footer">Data.gouv.fr</a><span>© Ministère de l’Éducation nationale · Licence Etalab 2.0</span></div></div></div></footer>
      {cookies && <aside className="cookie" aria-labelledby="cookie-title"><button className="cookie-close" onClick={() => setCookies(false)} aria-label="Fermer la gestion des cookies"><X size={18} /></button><h2 id="cookie-title">Bienvenue sur le site de l’Éducation nationale</h2><p>Nous utilisons des cookies pour mesurer l’audience, améliorer le fonctionnement du site et évaluer nos campagnes. Votre choix est conservé pendant 13 mois.</p>{cookieDetail && <p><strong>Personnaliser :</strong> les cookies essentiels restent actifs ; les cookies de mesure d’audience sont désactivés par défaut.</p>}<a className="blue-link" href="#footer">En savoir plus sur les données personnelles et les cookies</a><div className="cookie-actions"><button className="primary" onClick={() => setCookies(false)}><Check size={15} /> Tout accepter</button><button onClick={() => setCookies(false)}>Tout refuser</button><button onClick={() => setCookieDetail(v => !v)} aria-expanded={cookieDetail}>{cookieDetail ? "Fermer les options" : "Personnaliser"} {cookieDetail ? <ChevronUp size={15} /> : <ChevronDown size={15} />}</button></div></aside>}
    </div>
  );
}

export default EducationHomepage;